#!/usr/bin/env node
/* build.js — ESM 소스들을 하나의 classic 스크립트(app/bundle.js)로 묶는다.
   목적: file://(더블클릭)에서도 열리게. ES 모듈 import는 file://서 CORS로 막히지만
   classic <script src>는 file://서도 로드됨. 소스(ESM)는 그대로 유지 → node:test 계속 동작.
   편집 후 `node build.js` 실행. */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;

// 의존성 순서대로 (앞 파일이 뒤 파일보다 먼저 정의돼야 함)
const FILES = [
  'core/esc.js',
  'core/volume.js',
  'core/darkglow/templates.js',
  'core/darkglow/sections.js',
  'core/darkglow/render.js',
  'core/packs/darkglow/packs.js',
  'app/store.js',
  'app/theme.js',
];

// 페이지들이 전역으로 필요로 하는 심볼
const PUBLICS = [
  'esc',
  'VOLUMES', 'TIERS', 'includesTier',
  'DG_TEMPLATES', 'PAGE_TYPE_LABEL', 'SECTIONS', 'renderComposed',
  'DARK_PACKS', 'DARK_PACK_BY_ID',
  'PT_LABEL', 'emptyData', 'getProjects', 'saveProjects', 'getProject',
  'upsertProject', 'deleteProject', 'newPage', 'createProject', 'addPage', 'deletePage',
  'movePage', 'pageTree',
  'currentTheme', 'setTheme', 'toggleTheme', 'mountThemeToggle', 'applySavedTheme',
];

function strip(src) {
  return src
    .split('\n')
    .filter((l) => !/^\s*import\s.+from\s+['"].+['"];?\s*$/.test(l)) // import 줄 제거
    .join('\n')
    .replace(/^export\s+/gm, ''); // export 키워드만 제거 (선언은 남김)
}

let out = '/* AUTO-GENERATED by build.js — 편집 금지. 소스: core/*, app/store.js, app/theme.js */\n';
out += '(function () {\n';
for (const f of FILES) {
  const src = fs.readFileSync(path.join(ROOT, f), 'utf8');
  out += `\n/* ===== ${f} ===== */\n` + strip(src) + '\n';
}
out += '\nObject.assign(window, { ' + PUBLICS.join(', ') + ' });\n';
out += '})();\n';

const dest = path.join(ROOT, 'app/bundle.js');
fs.writeFileSync(dest, out);
console.log('built', path.relative(ROOT, dest), '(' + out.length + ' bytes)');
