#!/usr/bin/env node
/* build-icons.cjs — assets/icons/*.svg → app/icons.js (아이콘 레지스트리 + icon() 헬퍼).
   사용: Figma 등에서 SVG를 assets/icons/<name>.svg 로 떨궈 넣고 `node build-icons.cjs` 실행.
   - 파일명(케밥) = 아이콘 이름. 하위폴더면 `folder/name` 키.
   - 색은 currentColor로 정규화 → CSS color/stroke로 제어. viewBox 유지, width/height 제거(헬퍼가 주입).
   classic script 산출물이라 file://에서도 동작. */
const fs = require('fs');
const path = require('path');
const ROOT = require('path').join(__dirname, '..');   /* scripts/ 하위 이동 — 루트 기준 유지 */
const SRC = path.join(ROOT, 'assets/icons');
const DEST = path.join(ROOT, 'app/icons.js');

function walk(dir, base) {
  let out = [];
  if (!fs.existsSync(dir)) return out;
  for (const f of fs.readdirSync(dir)) {
    const p = path.join(dir, f);
    const st = fs.statSync(p);
    if (st.isDirectory()) out = out.concat(walk(p, (base ? base + '/' : '') + f));
    else if (f.endsWith('.svg')) out.push({ key: (base ? base + '/' : '') + f.replace(/\.svg$/, ''), file: p });
  }
  return out;
}

function normalize(svg) {
  svg = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+xmlns:xlink="[^"]*"/g, '');
  // 루트 <svg ...>에서만 width/height 제거 (child rect 등의 크기는 보존)
  svg = svg.replace(/<svg\b[^>]*>/, function (tag) { return tag.replace(/\s+(width|height)="[^"]*"/g, ''); });
  return svg
    .replace(/stroke="#[0-9a-fA-F]{3,8}"/g, 'stroke="currentColor"')
    .replace(/stroke="(?!none)(black|#000000|#000)"/gi, 'stroke="currentColor"')
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .replace(/fill="(black|#000000|#000)"/gi, 'fill="currentColor"')
    .replace(/\s{2,}/g, ' ')
    .replace(/>\s+</g, '><')
    .trim();
}

const icons = walk(SRC, '');
icons.sort((a, b) => a.key.localeCompare(b.key));

const entries = icons.map((i) => {
  const svg = normalize(fs.readFileSync(i.file, 'utf8'));
  return '    ' + JSON.stringify(i.key) + ': ' + JSON.stringify(svg);
});

const out = `/* AUTO-GENERATED by build-icons.cjs — 편집 금지. 소스: assets/icons/*.svg (${icons.length}개)
   사용: icon('home',{size:18,cls:'nav-ic',stroke:1.7}) → <svg> 문자열. 색은 currentColor. */
(function () {
  var ICON = {
${entries.join(',\n')}
  };
  window.ICON = ICON;
  window.iconNames = function () { return Object.keys(ICON); };
  window.icon = function (name, opts) {
    opts = opts || {};
    var svg = ICON[name];
    if (!svg) return '';
    var size = opts.size || 20;
    // 루트 <svg>에 width/height/class/stroke-width 주입
    svg = svg.replace(/<svg\\b/, '<svg width="' + size + '" height="' + size + '"'
      + (opts.cls ? ' class="' + opts.cls + '"' : '')
      + (opts.stroke ? ' stroke-width="' + opts.stroke + '"' : ''));
    return svg;
  };
})();
`;

fs.writeFileSync(DEST, out);
console.log('built app/icons.js —', icons.length, 'icons');
