#!/usr/bin/env node
/* scripts/pack-spec.cjs — 팩 실물 표본 자동 추출
   팩 JS를 샌드박스에서 실행해 기본 덱/페이지를 렌더 → packs/<cat>/packs.X.sample.html 생성.
   sample.html = 전체 CSS 내장 자기완결 — 스타일 이식·외부 AI 첨부용 "완전한 표본".
   사용: node scripts/pack-spec.cjs          (주요 6팩)
        node scripts/pack-spec.cjs naver    (하나만) */
'use strict';
const vm = require('vm');
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

function sandboxRun(files) {
  const noop = () => {};
  const win = {};
  const sb = {
    window: win, console,
    document: { currentScript: null, createElement: () => ({ style: {}, setAttribute: noop, appendChild: noop }), addEventListener: noop },
    localStorage: { getItem: () => null, setItem: noop, removeItem: noop },
    navigator: { userAgent: 'pack-spec' },
    setTimeout: noop, clearTimeout: noop, requestAnimationFrame: noop,
  };
  sb.globalThis = sb; win.document = sb.document; win.localStorage = sb.localStorage;
  vm.createContext(sb);
  for (const f of files) vm.runInContext(fs.readFileSync(path.join(ROOT, f), 'utf8'), sb, { filename: f });
  return win;
}

const PACKS = {
  naver:   { files: ['app/charts.js', 'packs/ppt/packs.naver.js'],   out: 'packs/ppt/packs.naver.sample.html',   render: (w) => w.renderNaverDeck({}) },
  rams:    { files: ['app/charts.js', 'packs/ppt/packs.rams.js'],    out: 'packs/ppt/packs.rams.sample.html',    render: (w) => w.renderRamsDeck({}) },
  machine: { files: ['app/charts.js', 'packs/ppt/packs.machine.js'], out: 'packs/ppt/packs.machine.sample.html', render: (w) => w.renderMachineDeck({}) },
  mbm:     { files: ['packs/web/packs.mbm.js'],   out: 'packs/web/packs.mbm.sample.html',   render: (w) => w.renderMbmPage({}, { volume: 'heavy', motion: 'static' }) },
  axday:   { files: ['packs/web/packs.axday.js'], out: 'packs/web/packs.axday.sample.html', render: (w) => w.renderAxdayPage({}, { volume: 'heavy', motion: 'static' }) },
  orbit:   { files: ['packs/web/packs.orbit.js'], out: 'packs/web/packs.orbit.sample.html', render: (w) => w.renderOrbitPage({}, { volume: 'heavy', motion: 'static' }) },
};

const only = process.argv[2];
let fail = 0;
for (const [id, p] of Object.entries(PACKS)) {
  if (only && id !== only) continue;
  try {
    const html = p.render(sandboxRun(p.files));
    if (!html || html.length < 5000) throw new Error('출력이 비정상적으로 짧음: ' + (html || '').length);
    const note = '<!-- AUTO-GENERATED by scripts/pack-spec.cjs — 편집 금지. 팩 기본 데이터의 실물 표본(전체 CSS 내장). 재생성: node scripts/pack-spec.cjs ' + id + ' -->\n';
    fs.writeFileSync(path.join(ROOT, p.out), note + html);
    console.log('✓ ' + p.out + '  (' + Math.round(html.length / 1024) + 'KB)');
  } catch (e) { fail = 1; console.error('✗ ' + id + ' — ' + e.message); }
}
process.exit(fail);
